app/models/applications.py
import app, bson

from app.db import db
from app.exceptions import *

class Applications():
    @staticmethod
    def create(user, title, description, link):
        result = mdb.applications.insert_one({
            'title': title,
            'description': description,
            'link': link,
            'user': {
                'id': user.id,
                'fname': user.fname,
                'lname': user.lname
            }
        })
        return result.inserted_id

    @staticmethod
    def update(application_id, title, description, link):
        application_id = bson.ObjectId(application_id)
        mdb.applications.update_one({'_id': application_id}, { '$set': {
            'title': title,
            'description': description,
            'link': link
        }})

    @staticmethod
    def fetch(user_id):
        if user_id is None:
            results = mdb.applications.find({})
        else:
            results = mdb.applications.find({'user.id': user_id})

        applications = []
        for result in results:
            result['id'] = str(result['_id'])
            applications.append(result)
        return applications

    @staticmethod
    def fetch_all():
        results = mdb.applications.find({})

        applications = []
        for result in results:
            result['id'] = str(result['_id'])
            applications.append(result)
        return applications

    @staticmethod
    def fetch_one(application_id):
        application_id = bson.ObjectId(application_id)
        result = mdb.applications.find_one({'_id': application_id})
        if result is None:
            return None
        result['id'] = str(result['_id'])
        return result


    @staticmethod
    def delete_one(application_id):
        application_id = bson.ObjectId(application_id)
        result = mdb.applications.delete_one({'_id': application_id})
        if result is None:
            return None
        return result

app/views/conteno.py
import app
import os, json, datetime, bson
from flask import Blueprint, g
from flask import render_template, request, jsonify, flash, url_for, redirect
from flask.ext.login import login_user, logout_user, login_required

from app.exceptions import *
from app.oauth import OAuthSignIn

from app.db import db
from app.mail import emails
from app.models.resources import Resources
from app.models.applications import Applications

from werkzeug import secure_filename

mod = Blueprint('conteno', __name__)

@mod.route('/', methods=["GET"])
@login_required
def index():
    return render_template('conteno_index.html')

@mod.route('/application/<application_id>/edit', methods=["GET", "POST"])
@login_required
def edit_application(application_id):
    next_url = request.args.get('next') or url_for('pages.index')
    if request.method == 'GET':
        app = Applications.fetch_one(application_id)
        if app is None:
            flash('Invalid application')
            return redirect(url_for('pages.applications'))

        if app['user']['id'] != g.user.id:
            flash('Application not found for user')
            return redirect(url_for('pages.applications'))

        return render_template('application.html', next_url=next_url, application=app)
    else:
        application_id = application_id
        title = request.form.get('title')
        description = request.form.get('description')
        link = request.form.get('link')

        if title is None or description is None:
            flash('Please fill all the mandatory fields.')
            return redirect(url_for('pages.new_application'))

        Applications.update(application_id, title, description, link)

        flash("Application details updated successfully")
        return redirect(url_for('pages.applications'))


@mod.route('/application/<application_id>/delete', methods=["GET"])
@login_required
def delete_application(application_id):
    next_url = request.args.get('next') or url_for('pages.index')
    if request.method == 'GET':
        app = Applications.fetch_one(application_id)

        if app is None:
            flash('Invalid application')
            return redirect(url_for('pages.applications'))

        if app['user']['id'] != g.user.id:
            flash('Application not found for user')
            return redirect(url_for('pages.applications'))

        Applications.delete_one(application_id)
        return redirect(url_for('pages.applications'))


@mod.route('/applications/all', methods=["GET"])
def applications():
    apps = Applications.fetch_all()
    return render_template('applications.html', applications=apps)


@mod.route('/applications/me', methods=["GET"])
@login_required
def user_applications():
    next_url = request.args.get('next') or url_for('pages.index')
    user_id = g.user.id
    apps = Applications.fetch(user_id)
    return render_template('applications.html', next_url=next_url, applications=apps)


@mod.route('/application/new', methods=["GET", "POST"])
@login_required
def new_application():
    next_url = request.args.get('next') or url_for('pages.index')
    if request.method == 'GET':
        return render_template('share.html', next_url=next_url)
    else:
        title = request.form.get('title')
        description = request.form.get('description')
        link = request.form.get('link')

        if title is None or description is None:
            flash('Please fill all the mandatory fields.')
            return redirect(url_for('pages.new_application'))

        Applications.create(g.user, title, description, link)

        flash("Your application is successfully published")
        return redirect(url_for('pages.applications'))


@mod.route('/suggestions', methods=["GET", "POST"])
def suggestions():
    if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email')
        message = request.form.get('message')
        emails.suggestion_email(name, email, message)
        flash('Thank you for contacting us :)')
        return redirect(url_for('pages.index'))
    else:
        return render_template('suggestions.html')


@mod.route('/help', methods=["GET"])
def help():
    next_url = request.args.get('next') or url_for('pages.index')
    return render_template('help.html', next_url=next_url)


@mod.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('pages.index'))


@mod.route('/generate', methods=["GET", "POST"])
@login_required
def generate():
    if request.method == 'POST':
        import bson, base64
        api_key = base64.b64encode(str(bson.ObjectId()))

        user_id = g.user.id
        user = LUser.query.get(user_id)
        user.api_key = g.user.id + api_key
        db.session.commit()

        flash('Your API key has been generated.')

    return render_template('generate.html')


@mod.route('/<media_type>/<genre>', methods=["GET"])
def fetch(media_type, genre):
    if media_type not in app.config.SUPPORTED_MEDIATYPES:
        raise UnsupportedException('Media type %s is not supported' % media_type)
    if genre not in app.config.SUPPORTED_GENRE:
        raise UnsupportedException('Genre %s is not supported' % genre)

    api_key = request.args.get('api_key')
    if api_key is None:
        raise UnsupportedException('API Key is missing')

    resource = Resources.fetch(api_key, media_type, genre)
    if resource is None:
        raise ResourceExhaustException('Resources exhausted for media_type: %s and genre: %s' % (media_type, genre))

    return jsonify(media_type=media_type, content=resource)


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1] in app.config.ALLOWED_EXTENSIONS


@mod.route('/add', methods=["GET", "POST"])
def add():
    if request.method == 'GET':
        return render_template('add.html', \
            media_types=app.config.SUPPORTED_MEDIATYPES, \
            genres=app.config.SUPPORTED_GENRE)
    else:
        attachment = request.files['attachment']
        media_type = request.form.get('media_type')
        genre = request.form.get('genre')

        if not media_type or not genre or not attachment:
            flash('Please fill all mandatory fields')
            return redirect(url_for('pages.add'))

        if media_type not in app.config.SUPPORTED_MEDIATYPES:
            raise UnsupportedException('Media type %s is not supported' % media_type)
        if genre not in app.config.SUPPORTED_GENRE:
            raise UnsupportedException('Genre %s is not supported' % genre)

        destination = None
        if attachment and allowed_file(attachment.filename):
            filename = secure_filename(attachment.filename)
            destination = os.path.join(app.config.UPLOAD_FOLDER, filename)
            attachment.save(destination)

        if destination is None:
            raise DevilException('Something went wrong, please upload your \
                content again')

        # Add the content of the file into database
        with open(destination, 'rb') as inputfile:
            items = json.loads(inputfile.read())
            ids, failed_items = Resources.update(media_type, genre, items)

        os.remove(destination)
        return jsonify(inserted_ids=ids, failed_items=failed_items)

app/views/pages.py
import app
import os, json, datetime, bson
from flask import Blueprint, g
from flask import render_template, request, jsonify, flash, url_for, redirect
from flask.ext.login import login_user, logout_user, login_required

from app.exceptions import *
from app.oauth import OAuthSignIn

from app.db import db
from app.mail import emails
from app.models.user import Profile

mod = Blueprint('pages', __name__, )

@mod.route('/', methods=["GET"])
def index():
    next_url = request.args.get('next') or url_for('pages.index')
    return render_template('index.html', next_url=next_url)

@mod.route('/login', methods=["GET"])
def login():
    next_url = request.args.get('next') or url_for('pages.index')
    return render_template('login.html', next_url=next_url)

@mod.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('pages.index'))

@mod.route('/authorize/<provider>')
def oauth_authorize(provider):
    if not g.user.is_anonymous:
        return redirect(url_for('pages.index'))

    next_url = request.args.get('next') or url_for('pages.index')
    oauth = OAuthSignIn.get_provider(provider)
    return oauth.authorize(next_url)

@mod.route('/callback/<provider>')
def oauth_callback(provider):
    next_url = request.args.get('next') or url_for('pages.index')
    if not g.user.is_anonymous:
        return redirect(url_for('pages.index'))
    oauth = OAuthSignIn.get_provider(provider)

    social_id, fname, lname, email = oauth.callback(next_url)

    if social_id is None:
        flash('Authentication failed.')
        return redirect(url_for('pages.index'))

    try:
        user = Profile.objects.get(email=email)
    except Profile.DoesNotExist:
        user = None

    if not user:
        name = "%s %s" %(fname, lname)
        user = Profile(social_id=social_id, name=name, email=email,\
            created_at=datetime.datetime.now())
        user.save()

        emails.welcome_email(user.name, user.email)
    else:
        user.last_login = datetime.datetime.now()
        user.save()

    login_user(user, True)
    return redirect(next_url)

app/templates/add.html
{% extends "raw.html" %}

{% block body %}
<div class="ui three column grid" style="padding-top: 150px;">
    <div class="column"></div>
    <form class="ui form" enctype="multipart/form-data" action="{{url_for('conteno.add')}}" method="POST">
        <div class="two fields">
            <div class="field required">
                <label>Media Types</label>
                <select class="ui dropdown" name="media_type">
                    {% for media_type in media_types %}
                    <option value={{media_type}}>{{media_type}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="field required">
                <label>Genres</label>
                <select class="ui dropdown" name="genre">
                    {% for genre in genres %}
                    <option value={{genre}}>{{genre}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="fluid field required">
            <div class="ui action input">
                <input type="text" id="_attachment">
                <label for="attachment" class="ui icon button btn-file">
                    Browse
                    <input type="file" id="attachment" name="attachment" style="display: none">
                </label>
            </div>
        </div>
        <input type="submit" class="ui blue button" value="Update">
    </form>
</div>
{% endblock %}

{% block head %}
<script src="/static/js/index.js"></script>
{% endblock %}

app/templates/application.html
{% extends "raw.html" %}

{% block body %}
<div class="ui grid" style="padding-top: 150px;">
    <div class="row">
        <div class="three wide column"></div>
        <div class="ten wide column">
            <form class="ui form" method="POST" action="{{url_for('conteno.edit_application', application_id=application._id)}}" id="share_form">
                <div class="field required">
                    <label>Title</label>
                    <input type="text" name="title" placeholder="Title for your application" value={{application.title}}>
                </div>
                <div class="field required">
                    <label>Description</label>
                    <input type="text" name="description" placeholder="One liner description" value="{{application.description}}">
                </div>
                <div class="field">
                    <label>Link</label>
                    <input type="text" name="link" placeholder="Source code link" value="{{application.link}}">
                </div>
                <input type="submit" value="Save" class="ui black button">
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block head %}
{% endblock %}

app/templates/applications.html
{% extends "raw.html" %}

{% block body %}
<div class="ui grid" style="padding-top: 150px;">
    <div class="row">
        <div class="three wide column"></div>
        <div class="ten wide column">
            <div class="ui black large header">
                {%- if request.path == url_for('conteno.user_applications') %}
                    <i><span class="ui red">You crated {{applications|length}}</span> application(s) ... we would love if you create more</i>
                {% else %}
                    <i><span class="ui red">{{applications|length}}</span> application(s) created</i>
                {% endif %}
            </div>
            <div class="section ui divider"></div>
            <div class="ui divided relaxed items">
                {% for application in applications %}
                <div class="item">
                    <div class="ui tiny image">
                        <i class="very huge cube icon"></i>
                    </div>
                    <div class="content">
                        {% if application.link %}
                            <a href="{{application.link}}" class="header">{{application.title}}</a>
                        {% else %}
                            <div class="header">{{application.title}}</div>
                        {% endif %}
                        <div class="meta">
                            <span>Author: <a href="/">{{application.user.fname}} {{application.user.lname}}</a></span>
                        </div>
                        <div class="description">
                            <p>{{application.description}}</p>
                        </div>
                    </div>
                    <div class="ui tiny image">
                        {% if application.user.id == g.user.id %}
                            <a href="{{url_for('conteno.delete_application', application_id=application.id)}}"><i class="large delete icon"></i></a>
                            <a href="{{url_for('conteno.edit_application', application_id=application.id)}}"><i class="large edit icon"></i></a>
                        {% endif%}
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<div class="ui grid center aligned" style="padding-top: 30px;">
    <div class="row">
        <div class="sixteen wide column">
            <div class="ui black large header">
                Did you also create something cool with our API?
            </div>
            <a class="ui huge black button" href="{{url_for('conteno.new_application')}}">
                Share it with us <i class="right arrow icon"></i>
            </a>
        </div>
    </div>
</div>
{% endblock %}

{% block head %}
{% endblock %}

app/templates/conteno_index.html
{% extends "raw.html" %}

{% block body %}
{% if g.user.api_key %}
<div class="ui grid" style="padding-top: 150px;">
    <div class="row">
        <div class="three wide column">
        </div>
        <div class="ten wide column">
            <div class="ui black header">
                Do a HTTP GET on the following URL
            </div>
            <pre class="my">
http://codeville.org.in/conteno/&lt;media_type&gt;/&lt;genre&gt;?api_key=&lt;api_key&gt;
            </pre>
        </div>
    </div>

    <div class="row">
        <div class="three wide column">
        </div>
        <div class="ten wide column">
            <div class="ui black header">
                For example
            </div>
            <pre class="my">
http://codeville.org.in/conteno/image/love?api_key={{g.user.api_key}}
            </pre>
        </div>
    </div>
</div>
<div class="ui center aligned grid">
    <div class="column">
        <a class="ui huge black button" href="{{url_for('conteno.help', _anchor='media-types')}}">
            Checkout media types we support <i class="right arrow icon"></i>
        </a>
    </div>
</div>
{% else %}
<div class="ui center aligned grid" style="padding-top: 150px;">
    <div class="column">
        <a class="ui huge black button" href="{{url_for('conteno.generate')}}">
            Generate an API Key here <i class="right arrow icon"></i>
        </a>
    </div>
</div>
{% endif %}
{% endblock %}

{% block head %}
{% endblock %}

app/templates/generate.html
{% extends "raw.html" %}

{% block body %}
<div class="ui grid" style="padding-top: 150px;">
    <div class="three wide column">
    </div>
    <div class="ten wide column">
        <div class="ui center aligned basic segment">
            <div class="ui big label center aligned">
                Genarating a new API key will make all of your previous keys nonfunctional.
            </div>
        </div>
        <form class="ui form" method="POST" action="{{url_for('conteno.generate')}}">
            <div class="ui action fluid input">
                <input style="font-family: 'Courier';" type="text" placeholder="" readonly="" id="api_key" value="{% if g.user.api_key %}{{g.user.api_key}}{% endif %}">
                <button type="submit" class="ui black button">Generate new API Key</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block head %}
{% endblock %}

app/templates/index.html
{% extends "raw.html" %}

{% block body %}
<div class="" style="min-height:700px;">
    <div class="ui section hidden divider"></div>
    <div class="ui grid">
        <div class="column">
            <img class="ui centered small image" src="/static/images/myAvatar.png" style="padding-top: 90px;">
        </div>
    </div>
    <div class="ui grid">
        <div class="row">
            <div class="sixteen wide column">
                <div class="ui hidden divider"></div>
                <div class="ui large header center aligned">
                    <a class="ui huge red button center aligned" href='/quora'>
                        Quora - Widget
                    </a>
                </div>
                <div class="ui hidden divider"></div>
            </div>
        </div>
        <div class="row">
            <div class="sixteen wide column">
                <div class="ui large header center aligned">
                    Designed and developed with <span><i class="heart red icon"></i></span>by <a href="http://arpitbbhayani.github.io/about-me" style="font-family: 'Just Me Again Down Here', cursive;">Arpit</a>
                </div>
            </div>
        </div>
        {% if not g.user.is_authenticated %}
        <div class="row">
            <div class="sixteen wide column">
                <div class="ui large header center aligned">
                    <span>
                        Sign up and explore <i class="right arrow icon"></i>
                        <a class="ui huge facebook button" href="{{url_for('pages.oauth_authorize', provider='facebook', next=next_url)}}">
                            <i class="facebook icon"></i>
                            Login with Facebook
                        </a>
                    </span>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/intro.html
<div class="" style="min-height:700px;">
    <div class="ui grid">
        <div class="column">
            <img class="ui centered small image" src="/static/images/myAvatar.png" style="padding-top: 90px;">
        </div>
    </div>
    <div class="ui grid">
        <div class="row">
            <div class="sixteen wide column">
                <div class="ui large header center aligned">
                    Get <span class="shouldbe">awesome</span> content with one REST API
                </div>
            </div>
        </div>
        <div class="ui section hidden divider"></div>
        <div class="row">
            <div class="sixteen wide column">
                <div class="ui large header center aligned">
                    Designed and developed with <span><i class="heart red icon"></i></span>by <a href="http://arpitbbhayani.github.io/about-me" style="font-family: 'Just Me Again Down Here', cursive;">Arpit</a>
                </div>
            </div>
        </div>
        <div class="ui section hidden divider"></div>
        <div class="row">
            <div class="sixteen wide column">
                <div class="ui large header center aligned">
                    <span>
                        Sign up and explore <i class="right arrow icon"></i>
                        <a class="ui huge facebook button" href="{{url_for('pages.oauth_authorize', provider='facebook', next=next_url)}}">
                            <i class="facebook icon"></i>
                            Login with Facebook
                        </a>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>
<footer>
    <div class="section hidden divider ui"></div>
    <div class="ui center aligned grid">
        <div class="column">
            <div>Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a>             is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0">CC BY 3.0</a></div>
        </div>
    </div>
</footer>

<script>
var index = 0;
var wordlist = ['awesome', 'amazing', 'meaningful', 'kickass'],
randomWordInt;

function changeWord(){
    randomWordInt = setInterval(randomWord, 3000);
}

function randomWord() {
    index  = index + 1;
    index = index % wordlist.length;
    var i = index;
    var shouldBe = wordlist[i];
    $('.shouldbe').fadeOut('fast', function(){
        $('.shouldbe').text(shouldBe);
    });
    $('.shouldbe').fadeIn('fast');
}
changeWord();
</script>

app/templates/login.html
{% extends "raw.html" %}

{% block body %}
<div class="" style="min-height:700px;">
    <div class="ui section hidden divider"></div>
    <div class="ui grid">
        <div class="column">
            <img class="ui centered small image" src="/static/images/myAvatar.png" style="padding-top: 90px;">
        </div>
    </div>
    <div class="ui grid">
        <div class="row">
            <div class="sixteen wide column">
                <div class="ui hidden divider"></div>
                <div class="ui large header center aligned">
                    <a class="ui huge teal button" href='/conteno'>
                        Conteno
                    </a>
                    <a class="ui huge red button center aligned" href='/quora'>
                        Quora - Widget
                    </a>
                </div>
                <div class="ui hidden divider"></div>
            </div>
        </div>
        <div class="row">
            <div class="sixteen wide column">
                <div class="ui large header center aligned">
                    Designed and developed with <span><i class="heart red icon"></i></span>by <a href="http://arpitbbhayani.github.io/about-me" style="font-family: 'Just Me Again Down Here', cursive;">Arpit</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="sixteen wide column">
                <div class="ui large header center aligned">
                    <span>
                        Sign up and explore <i class="right arrow icon"></i>
                        <a class="ui huge facebook button" href="{{url_for('pages.oauth_authorize', provider='facebook', next=next_url)}}">
                            <i class="facebook icon"></i>
                            Login with Facebook
                        </a>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/raw.html
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Codeville</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" sizes="57x57" href="/static/images/icons/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/static/images/icons/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/static/images/icons/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/static/images/icons/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/static/images/icons/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/static/images/icons/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/static/images/icons/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/static/images/icons/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/static/images/icons/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/static/images/icons/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/images/icons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/static/images/icons/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/images/icons/favicon-16x16.png">
    <link rel="manifest" href="/static/images/icons/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/static/images/icons/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" href="/static/semantic/dist/semantic.min.css">

    <!-- JS Libs -->
    <script src="/static/js/lib/jquery-1.11.3.min.js"></script>
    <script src="/static/semantic/dist/semantic.min.js"></script>
</head>

<body>
    <div class="ui fixed borderless menu" style="{% if not g.user.is_authenticated %}background: transparent;{% endif %}">
        <div class="penny-header item">
            <span><a href="{{url_for('pages.index')}}" class="header black ui"><h2>Codeville</h2></a></span>
        </div>
        <div class="right menu item">
            {% if not g.user.is_authenticated %}
            <div class="item">
                <a class="ui huge facebook button" href="{{url_for('pages.oauth_authorize', provider='facebook', next=next_url)}}">
                    <i class="facebook icon"></i>
                    Login with Facebook
                </a>
            </div>
            {% else %}
            <div class="ui dropdown item">
                <i class="user icon"></i>
                Hi, {{ g.user.name }} <i class="dropdown icon"></i>
                <div class="menu">
                    <span class="disabled item">{{ current_user.email }}</span>
                    {% if request.path[:8] == '/conteno' %}
                    <a class="item" href="{{ url_for('conteno.user_applications') }}">
                        <i class="cubes icon"></i> My Applications
                    </a>
                    <a class="item" href="{{ url_for('conteno.generate') }}">
                        <i class="refresh icon"></i> Generate new API Key
                    </a>
                    <a class="item" href="{{ url_for('conteno.help') }}">
                        <i class="help icon"></i> Help
                    </a>
                    {% endif %}
                    <a class="item" href="{{ url_for('conteno.logout') }}">
                        <i class="sign out icon"></i> Logout
                    </a>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
    <div id="msg" class="ui message" style="display: none;"></div>
    {% with messages = get_flashed_messages() %}
      {% if messages %}
          <div class="ui message" id="flashes">
              <ul>
                  {% for message in messages %}
                  <li>{{ message }}</li>
                  {% endfor %}
              </ul>
          </div>
      {% endif %}
    {% endwith %}
    {% block body %}{% endblock %}
</body>
<head>
{% block head %}{% endblock %}
<!-- UX Styling -->
<link href='https://fonts.googleapis.com/css?family=Allerta+Stencil' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="/static/css/ux.css">
<script src="/static/js/index.js"></script>
<script src="/static/js/uimodules.js"></script>
</head>
</html>

app/templates/share.html
{% extends "raw.html" %}

{% block body %}
<div class="ui grid" style="padding-top: 150px;">
    <div class="row">
        <div class="three wide column"></div>
        <div class="ten wide column">
            <form class="ui form" method="POST" action="{{url_for('conteno.new_application')}}" id="share_form">
                <div class="field required">
                    <label>Title</label>
                    <input type="text" name="title" placeholder="Title for your application">
                </div>
                <div class="field required">
                    <label>Description</label>
                    <input type="text" name="description" placeholder="One liner description" value="">
                </div>
                <div class="field">
                    <label>Link</label>
                    <input type="text" name="link" placeholder="Source code link" value="">
                </div>
                <input type="submit" value="Publish" class="ui black button">
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block head %}
{% endblock %}